server:
  port: 8080
spring:
  datasource:


    url: jdbc:postgresql://localhost:${db_port_number:5432}/${db:decablog}
    password: ${PASSWORD:}
    username: ${USERNAME:postgres}


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    show-sql: false
  main:
    allow-circular-references: true

cloud_name: dnfi4vceq
api_key: 327853175254297
api_secret: XlvN0SKt7_CfDbJoi22DqkO4pMU

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB






